import type {
  Reservation,
  CharterReservation,
  News,
  ClosedDay,
} from "@/types";

export const DUMMY_RESERVATIONS: Reservation[] = [
  {
    id: "res_001",
    visitDate: "2026-03-05",
    visitTime: "10時頃",
    isWeekday: true,
    guestName: "山田 太郎",
    phone: "090-0000-0001",
    email: "yamada@example.com",
    adultCount: 2,
    estimatedFee: 1100,
    vaccineConfirmed: true,
    status: "RECEIVED",
    note: "",
    dogs: [
      { id: "dog_001", name: "ハナ", breed: "ボーダーコリー", size: "MEDIUM", gender: "FEMALE" },
      { id: "dog_002", name: "クロ", breed: "ミックス（中型）", size: "MEDIUM", gender: "MALE" },
    ],
  },
  {
    id: "res_002",
    visitDate: "2026-03-05",
    visitTime: "13時頃",
    isWeekday: true,
    guestName: "鈴木 花子",
    phone: "080-0000-0002",
    email: "suzuki@example.com",
    adultCount: 1,
    estimatedFee: 800,
    vaccineConfirmed: true,
    status: "CONFIRMED",
    note: "大型犬です",
    dogs: [
      { id: "dog_003", name: "ゴン", breed: "ゴールデンレトリバー", size: "LARGE", gender: "MALE" },
    ],
  },
  {
    id: "res_003",
    visitDate: "2026-03-06",
    visitTime: "9時頃",
    isWeekday: true,
    guestName: "佐藤 美咲",
    phone: "090-0000-0004",
    email: "sato@example.com",
    adultCount: 1,
    estimatedFee: 800,
    vaccineConfirmed: true,
    status: "RECEIVED",
    note: "",
    dogs: [
      { id: "dog_005", name: "ポチ", breed: "柴犬", size: "MEDIUM", gender: "MALE" },
    ],
  },
  {
    id: "res_004",
    visitDate: "2026-03-08",
    visitTime: "10時頃",
    isWeekday: false,
    guestName: "高橋 一郎",
    phone: "090-0000-0005",
    email: "takahashi@example.com",
    adultCount: 2,
    estimatedFee: 1400,
    vaccineConfirmed: true,
    status: "CONFIRMED",
    note: "",
    dogs: [
      { id: "dog_006", name: "ソラ", breed: "トイプードル", size: "SMALL", gender: "MALE" },
      { id: "dog_007", name: "ルナ", breed: "チワワ", size: "SMALL", gender: "FEMALE" },
    ],
  },
  {
    id: "res_005",
    visitDate: "2026-03-08",
    visitTime: "11時頃",
    isWeekday: false,
    guestName: "渡辺 恵",
    phone: "080-0000-0006",
    email: "watanabe@example.com",
    adultCount: 1,
    estimatedFee: 1000,
    vaccineConfirmed: true,
    status: "RECEIVED",
    note: "",
    dogs: [
      { id: "dog_008", name: "リク", breed: "ラブラドールレトリバー", size: "LARGE", gender: "MALE" },
    ],
  },
  {
    id: "res_006",
    visitDate: "2026-03-12",
    visitTime: "14時頃",
    isWeekday: true,
    guestName: "中村 真",
    phone: "070-0000-0007",
    email: "nakamura@example.com",
    adultCount: 1,
    estimatedFee: 800,
    vaccineConfirmed: true,
    status: "RECEIVED",
    note: "",
    dogs: [
      { id: "dog_009", name: "マル", breed: "ウィペット", size: "MEDIUM", gender: "FEMALE" },
    ],
  },
  {
    id: "res_007",
    visitDate: "2026-03-21",
    visitTime: "10時頃",
    isWeekday: false,
    guestName: "伊藤 健太",
    phone: "090-0000-0008",
    email: "ito@example.com",
    adultCount: 2,
    estimatedFee: 1400,
    vaccineConfirmed: true,
    status: "CONFIRMED",
    note: "ディスクドッグ体験会に参加します",
    dogs: [
      { id: "dog_010", name: "レオ", breed: "ボーダーコリー", size: "MEDIUM", gender: "MALE" },
    ],
  },
];

export const DUMMY_CHARTERS: CharterReservation[] = [
  {
    id: "chr_001",
    visitDate: "2026-03-07",
    startTime: "10:00",
    hours: 3,
    charterFee: 6500,
    adultCount: 4,
    estimatedUsageFee: 2200,
    guestName: "田中 次郎",
    phone: "070-0000-0003",
    email: "tanaka@example.com",
    vaccineConfirmed: true,
    policyAgreed: true,
    status: "CONFIRMED",
    note: "誕生日パーティーで利用します",
    dogs: [
      { id: "dog_004", name: "モモ", breed: "トイプードル", size: "SMALL", gender: "FEMALE" },
    ],
  },
  {
    id: "chr_002",
    visitDate: "2026-03-22",
    startTime: "13:00",
    hours: 2,
    charterFee: 5000,
    adultCount: 3,
    estimatedUsageFee: 1800,
    guestName: "小林 由美",
    phone: "080-0000-0009",
    email: "kobayashi@example.com",
    vaccineConfirmed: true,
    policyAgreed: true,
    status: "CONFIRMED",
    note: "",
    dogs: [
      { id: "dog_011", name: "ココ", breed: "フレンチブルドッグ", size: "SMALL", gender: "FEMALE" },
      { id: "dog_012", name: "テツ", breed: "パグ", size: "SMALL", gender: "MALE" },
    ],
  },
];

export const DUMMY_NEWS: News[] = [
  {
    id: "news_001",
    title: "3月15日（日）臨時休業のお知らせ",
    body: "誠に申し訳ございませんが、3月15日（日）は設備メンテナンスのため臨時休業とさせていただきます。\n\n翌16日（月）より通常営業いたします。\nご不便をおかけしますが、何卒ご了承ください。",
    publishedAt: "2026-03-01",
    published: true,
  },
  {
    id: "news_002",
    title: "春のディスクドッグ体験会開催！",
    body: "3月21日（土）に春のディスクドッグ体験会を開催します！\n\n初めてのワンちゃんでも大歓迎。ディスクドッグチャンピオンが丁寧に指導します。\n\n**日時**: 2026年3月21日（土）10:00〜12:00\n**対象**: 全犬種（ドッグラン利用料が別途かかります）\n**持ち物**: リード、お水、おやつ\n\nお問い合わせフォームからお気軽にお申し込みください。",
    publishedAt: "2026-02-20",
    published: true,
    eventDate: "2026-03-21",
  },
  {
    id: "news_003",
    title: "年末年始の営業について",
    body: "年末年始は12月31日〜1月2日まで休業いたします。1月3日から通常営業です。",
    publishedAt: "2025-12-20",
    published: true,
  },
  {
    id: "news_004",
    title: "ドッグマッサージ体験デー",
    body: "3月28日（土）にドッグマッサージの無料体験デーを開催します。犬護舎流マッサージの技術を体感してみませんか？\n\n**日時**: 2026年3月28日（土）13:00〜15:00\n**対象**: 全犬種\n\n先着5組限定です。お問い合わせフォームよりお申し込みください。",
    publishedAt: "2026-03-05",
    published: true,
    eventDate: "2026-03-28",
  },
];

export const DUMMY_CLOSED_DAYS: ClosedDay[] = [
  { date: "2026-03-15", reason: "設備メンテナンス" },
];
